### ISSUE TITLE
Imposible to start New Request

### ISSUE THREAD

**Issue by soaswfactory** [Bonitasoft-Community/procurement-example#1]
There is a problem when trying to create a New procurement request. It happens because in the following line, which is in the pbButton directive, is not possible to obtain ID of the Process because URL belongs to an Application not the full Bonita Portal and so, the ID is not available:

else if ($scope.properties.action === "Start process") {
      id = getUrlParam('id');

Regards,

Quauhtli

**Comment by soaswfactory** [comment]
I had to hardocode process ID genereted in my Bonita installation as following:

```
  id = getUrlParam('id');
  id = "6503211496962221859";
```

**Comment by pozil** [comment]
Hi,

In order to best answer, can you please give me the following information:
- the Bonita BPM version that you are using
- the Procurement example version that you are using
- the possible JS errors that are displayed on your browser's developer console

Cheers,

**Comment by soaswfactory** [comment]
Bonita 7.0.2
Last version (downloaded yesterday)
There is no error in the console because you're handling the exception it just displays "Impossible to retrieve the process definition id value from the URL".

**Comment by pozil** [comment]
After struggling to reproduce the issue I figured out that the bug you are reporting is not present in Chrome 44. However, Internet Explorer 11 and Firefox 40 are both affected.

I discovered that the bug is not related to the pbDirective.
The issue comes from the custom list transfer widget that allows to select suppliers. For some unknown reason, the form page is refreshed when we select the first supplier and the form iFrame URL changes (you may notice that the pages blinks).
The new URL is invalid as it no longer contains the process id. This is why you get the error when trying to submit the form.

I will report the issue to our R&D team and see what can be done to fix it.

**Comment by soaswfactory** [comment]
Cool!

In fact, I noticed that bug as well just thought it was another one. Please let us know when you fix this.

Thanks!

**Comment by pozil** [comment]
I have fixed the bug in the Procurement example.
Please download the [latest release](https://github.com/Bonitasoft-Community/procurement-example/releases) to get the fix.
